name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: |
       echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"  
    - name: install dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen pkg-config libssl-dev libsodium-dev
    - name: build
      run: make -j2
