name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt -y install build-essential cmake graphviz doxygen pkg-config libssl-dev libsodium-dev
    - name: build
      run: cmake -S . -B build -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include -DDISABLE_SNODE_SIGNATURE=OFF -DCMAKE_BUILD_TYPE=Release ..
    - name: build cmake
      run: cmake --build .
